# http
PUT http://localhost:4000/api/article/update HTTP/1.1
content-type: application/json

{
    "_id": "607a03d1d86b02ffe4364971",
    "title": "updat tehtlriekhg",
    "description": "update !!!!",
    "author": "Anonymous Update"
}
